{{- if .Values.dockerConfigJson -}}

apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson }}
kind: Secret
metadata:
  creationTimestamp: null
  name: github-pull-secret
type: kubernetes.io/dockerconfigjson

{{- end -}}
